function get_all_talks(){
  return [
    [// day 1
      [// part 1
        {// plenary talk
          speaker: "Mikhail Khovanov",
          university: "",
          title: "Webs and foams in historical perspective",
          description: "We will recall how webs appear in the theory of quantum invariants and discuss their categorifications via matrix factorizations and foams. Some open problems in this theory will be reviewed.",
          start: "2025-02-01T12:00:00Z",
          duration: 1.0,
        },
        [// section 1
          {
            speaker: "Seiichi Kamada",
            university: "",
            title: "Generalized Alexander Quandles and Their Classification",
            description: "Generalized Alexander quandles, also known as principal quandles, form a special class of homogeneous quandles. Recently, Akihiro Higashitani and Hirotake Kurihara established a characterization theorem for finite generalized Alexander quandles under certain assumptions and classified those with up to 15 elements. In this talk, we build upon their work by providing a broader characterization of generalized Alexander quandles, relaxing the assumptions of finiteness and other restrictive conditions. Furthermore, we classify these quandles with up to 127 elements. This is joint work with Akihiro Higashitani, Jin Kosaka, and Hirotake Kurihara.",
            start: "2025-02-01T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Zhiyun Cheng",
            university: "Beijing Normal University",
            title: "Partial-dual genus polynomial and its categorification",
            description: "The partial-dual genus polynomial of a ribbon graph is the generating function that enumerates all partial duals of the ribbon graph.<br/><br/>In this talk, I will give an introduction to this polynomial and discuss the categorification of it. This is a joint work with Ziyi Lei.",
            start: "2025-02-01T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Mikami Hirasawa",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-01T13:00:00Z",
            duration: 1.0,
          }
        ],
        [// section 2
          {
            speaker: "Naoko Kamada",
            university: "Nagoya City University",
            title: "A Method for Constructing Welded Links from Existing Welded Links",
            description: "A welded link is defined as an equivalence class of welded link diagrams under the equivalence relation generated by classical Reidemeister moves, virtual Reidemeister moves, and welded moves. In this talk, we introduce a method for constructing a new welded link diagram from an existing one, ensuring that if two original diagrams are equivalent, the constructed diagrams are also equivalent. This defines a self-map on the set of welded links. A notable feature of our method is that even if the initial diagram is classical, the resulting diagram is not necessarily classical.<br/><br/>This work is a collaboration with Seiichi Kamada.",
            start: "2025-02-01T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Sam Nelson",
            university: "",
            title: "Quandle Cohomology Quiver Representations",
            description: "Quandles are algebraic structures encoding the motion of knots through space. Quandle cocycle quivers categorify the quandle cocycle invariant. In this talk we will define a quiver representation associated to quandle cocycle quivers and use it to obtain new polynomial invariants of knots.",
            start: "2025-02-01T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Alessia Cattabriga",
            university: "",
            title: "Plat-like representation of links in $3$-manifolds",
            description: "In this talk, I will present some results on link representations in $3$-manifolds that generalize the well-known plat closure representation in the 3-sphere. More specifically, one representation involves the Heegaard decomposition of manifolds and surface braids, and it applies to links in all closed, connected, orientable $3$-manifolds (joint work with Paolo Bellingeri and Boštjan Grabrovšek). The other representation also utilizes surface braids but is applicable to links in $3$-manifolds containing a non-orientable embedded surface whose complement is a handlebody<br/><br/>Joint work with Paolo Cavicchioli, Visakh Narayanan, and Misha Rama.",
            start: "2025-02-01T14:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 2
        {// plenary talk
          speaker: "Jacob Rasmussen",
          university: "",
          title: "Satellite operators, curves, and the Fukaya category",
          description: "The Alexander polynomial of a satellite knot is related to the Alexander polynomials of the pattern and companion by a simple and well-known formula. The analogous problem for the knot Floer homology has been studied for 20 years, starting with the work of Eftekhary and Hedden. A modern perspective on the problem is that the Floer homology of the pattern induces a functor from the Fukaya category of the punctured torus to itself. I'll discuss this functor and how we should think about it.",
          start: "2025-02-01T18:00:00Z",
          duration: 1.0,
        },
        {// plenary talk
          speaker: "Sergei Gukov",
          university: "",
          title: "Knot Theory and AI",
          description: "It comes as no surprise that solving challenging research-level math problems drives progress in mathematics. What is more surprising, though, is that solving such long-standing open problems also contributes to an entirely different field: the development of the next generation AI systems. We live in an exciting time where mathematics and AI can greatly benefit each other, and the goal of the talk is to explain how and why, drawing on specific examples from topology and knot theory.",
          start: "2025-02-01T19:00:00Z",
          duration: 1.0,
        },
        [
          {
            speaker: "Anatoly Libgober",
            university: "",
            title: "Geometric applications of Alexander invariants of the complements to algebraic curves",
            description: "One of the main results is a description of complex plane algebraic curves with the fundamental groups of the complements having free quotients of a large rank. The key technical tool is Alexander invariants which will be discussed in the beginning of the talk.",
            start: "2025-02-01T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Dominique Manchon",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-01T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Daniel Silver",
            university: "",
            title: "The Penrose Polynomial",
            description: "The Four Color Theorem states that no more than four colors are needed to color the regions of a map so that contingent regions receive different colors. The theorem was proved in 1976 by Kenneth Appel and Wolfgang Haken with the aid of a computer. A non-electronic proof remains elusive. In this joint work with Susan Williams and Louis Kauffman, we give a new description of a polynomial implicit in a 1969 paper by Roger Penrose. A complete understanding of the polynomial would result in a new proof of the Four Color Theorem.",
            start: "2025-02-01T20:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 3
        [
          {
            speaker: "Sonia Mahmoudi",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-02T01:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Marithania Silvero",
            university: "",
            title: "On a conjecture of Lou on alternative and pseudoalternating links",
            description: "In 1983 Louis Kauffman introduced the family of alternative links, as a generalization of alternating links. It is known that alternative links are pseudoalternating. Kauffman conjectured the converse. In this talk we show that both families are equal in the particular case of knots of genus one. However, Kauffman's Conjecture does not hold in general, as we also show by finding two counterexamples. In the way we will deal with the intermediate family of homogeneous links, introduced by Peter Cromwell; the techniques used here allow us to give an explicit characterization of homogeneous links of genus 1.",
            start: "2025-02-02T01:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Samuel Lomonaco",
            university: "",
            title: "How to build a device that cannot be built",
            description: "Our objective is to illustrate the weirdness of quantum mechanics with a concrete simple device that encapsulates the $GHZ$ paradox. We begin by defining this device in terms of engineering specs.<br/><br/>1. We then show that there is no way this device can be built using the laws of classical physics.<br/>2. However, we then show how it can be built within the laws of quantum physics.<br/><br/> In so doing, we come face-to-face with a concrete example of the $GHZ$ Paradox, a well known illustration of quantum entanglement weirdness.",
            start: "2025-02-02T01:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "Qiuyu Ren",
            university: "",
            title: "Lasagna s-invariant detect exotic $4$-manifolds",
            description: "We introduce a generalization of Rasmussen's $s$-invariant, called the lasagna $s$-invariant, which assigns either an integer or $-\\infty$ to each second homology class of a smooth $4$-manifold. The construction is based on the construction of skein lasagna modules by Morrison-Walker-Wedrich. We present a few properties enjoyed by lasagna $s$-invariants, and we show that they detect the exotic pair of knot traces $X_{-1}(-5_2)$ and $X_{-1}(P(3,-3,-8))$, an example first discovered by Akbulut. This gives the first gauge/Floer-theory-free proof of the existence of compact orientable exotic $4$-manifolds. This is joint work with Michael Willis.",
            start: "2025-02-02T02:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Alexander Stoimenow",
            university: "",
            title: "Strong quasipositivity, Thurston-Bennequin invariants, and arc index",
            description: "This talk gives a survey of recent work with several collaborators (mostly G.T.Jin and H.J.Lee, but also V.Singh) on establishing connections between the concepts in the title. Specifically, we relate to Rudolph's result about strong quasipositivity of annuli, the Livingston-Naik inequalities for jump numbers of slice-torus invariants, the Bennequin sharpness problem for Whitehead doubles, the Ohyama braid index inequality, and a recent result of Diao-Morton about the braid indices of reverse parallels of alternating knots.<br/><br/>We introduce an alternative approach towards estimating Thurston-Bennequin invariants and arc index of knots from link polynomials, with special discussion of torus knots.",
            start: "2025-02-02T02:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Mario Eudave-Munoz",
            university: "",
            title: "On hyperbolic knots with half-integral toroidal Dehn surgeries",
            description: "Many years ago the author constructed a family of hyperbolic knots $K(\\ell,m,n,p)$, with the property of having a half-integral toroidal Dehn surgery, that is, a $r/2$-Dehn surgery which produces a manifold containing an incompressible torus. This was done by means of the Montesinos trick, that is, by using sums of tangles and double branched covers. Now we give an explicit construction of a subfamily of these knots, so that we can see how the knots look in the 3-sphere. To do that, first we show an embedded handlebody $H$ in the 3-sphere, which is knotted, and such that there is a Möbius band $\\mathcal{M}$ properly embedded in its exterior, and such that the boundary of  $\\mathcal{M}$ intersects any meridian disk of $H$. The core of  $\\mathcal{M}$ is then the knot with the required Dehn surgery.",
            start: "2025-02-02T02:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "Seongjeong Kim",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-02T03:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Jessica Purcell",
            university: "",
            title: "Triangulations of the 3-sphere with knotted edge",
            description: "We prove that for any knot $K$, there exists a one-vertex triangulation of the 3-sphere containing an edge forming $K$. This result is related to open questions on triangulations of 3-manifolds. It has been known since work of Moise in the 1950s that every 3-manifold admits a triangulation, or decomposition into tetrahedra. However, the following are still unknown:<br/>(1) Given a hyperbolic 3-manifold, does it admit a geometric triangulation, i.e. a decomposition into ideal tetrahedra that are positively oriented and convex with respect to the given hyperbolic metric?<br/>(2) When is a triangulation minimal, i.e. uses the least number of tetrahedra required by its topology?<br/>In combinatorics and computational topology, there are additional questions along the lines of:<br/>(3) How bad can a triangulation be?<br/><br/>In this talk, I will discuss recent results on (3). While the statement of the result is purely topological, the proof uses hyperbolic geometry, and runs into questions (1) and (2).<br/><br/>This is joint with Ibarra, Mathews, and Spreer.",
            start: "2025-02-02T03:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Shin Satoh",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-02T03:00:00Z",
            duration: 1.0,
          }
        ]
      ]
    ],
    [// day 2
      [// part 1
        {// plenary talk
          speaker: "Victor Vassiliev",
          university: "Weizmann Institiute of Science",
          title: "Varieties of chord diagrams and finite dimensional knot spaces",
          description: "Every finite collection of <i>chords</i>, i.e. pairs of points $a_i \\neq b_i$ in ${\\mathbb R}^1$ or $S^1$, defines a subalgebra in $C^\\infty({\\mathbb R}^1, {\\mathbb R}) $ or $C^\\infty(S^1, {\\mathbb R})$ consisting of functions satisfying all conditions of the form $f(a_i) = f(b_i)$, $i=1, \\dots, d$. The space of all such subalgebras of a given codimension $d$ is a semialgebraic variety.<br/><br/>We will consider these varieties, their natural compactifications, and the canonical $d$-dimensional normal bundles on them. Lower bounds on the dimensions of non-trivial characteristic classes of these bundles will be given, and their implications in knot theory and interpolation theory will be discussed.",
          start: "2025-02-02T12:00:00Z",
          duration: 1.0,
        },
        [// section 1
          {
            speaker: "Alex Zupan",
            university: "",
            title: "Determining the ribbon numbers of ribbon knots",
            description: "There are two perspectives we often get on a ribbon disk for a knot $K$ in the $3$-sphere:<br/<br/>A ribbon disk is defined as either an immersed disk in $S^3$ with only ribbon self-intersections, or an embedded disk in $B^4$ with no maxima with respect to the radial Morse function.  These definitions are often called \"equivalent\", but more technically, the difference between them is like the difference between a knot and a knot diagram; one is an embedding, and the other is a lower-dimensional projection of an embedding.  The \"ribbon number\" $r(K)$ for a ribbon knot $K$ is the smallest number of ribbon intersections among any projection of any ribbon disk bounded by $K$, and $r(K)$ can then be seen as a sort of crossing number for ribbon disks.  The Alexander polynomial of $K$ can be used with rather surprising accuracy to give lower bounds for $r(K)$, and we discuss our work in understanding and cataloguing ribbon numbers for low-crossing ribbon knots.<br/><br/>Parts of this talk are joint with Stefan Friedl, Jeffrey Meier, Filip Misev, Evan Scott, and many undergraduate students.",
            start: "2025-02-02T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Slava Krushkal",
            university: "",
            title: "Thompson's group $F$, tangles, and link homology",
            description: "We extend a construction of V. Jones to associate $(n, n)$-tangles with elements of Thompson's group $F$ and prove that it is asymptotically faithful as $n \\to\\infty$. Using this construction we show that $F$ admits a lax group action on a category of Khovanov's chain complexes.<br/><br/>Joint work with Louisa Liles and Yangxiao Luo.",
            start: "2025-02-02T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Milagros Izquierdo",
            university: "",
            title: "One Dimensional Families of Riemann Surfaces with Automorphisms",
            description: "The moduli space $\\mathcal{M}_{g}$ of surfaces of genus $g\\geq 2$ is the space of conformal equivalence classes of closed Riemann surfaces of genus $g$. This space is a complex, quasi-projective variety of dimension $3g-3$, and geometrically an orbifold under the action of the modular group. The set of singular points, the <i>branch locus</i>, may be stratified into a finite, disjoint union of smooth, irreducible, quasi-projective subvarieties called <i>equisymmetric strata</i>. Each stratum corresponds to a collection of surfaces of the same <i>symmetry type</i>, i.e. the conjugacy class of a finite group in the modular group.<br/><br/>The (complex) 1D strata are Riemann surfaces with punctures. We study these strata as punctured Riemann surfaces, in terms of the action of the automorphism group of the surfaces in the stratum. In this way the strata can be constructed, a la Hurwitz, as (branched) coverings of the Riemann sphere with four punctures or a torus with one puncture. We see that such strata are in fact Belyi curves. It will be interesting to see which ones are given by regular dessins d'enfants.",
            start: "2025-02-02T13:00:00Z",
            duration: 1.0,
          }
        ],
        [// section 2
          {
            speaker: "Renzo Ricca",
            university: "U.  Milano-Bicocca",
            title: "A Topological Approach to Turbulence Cascade",
            description: "Fluid turbulence is a phenomenon characterised by the production of complex, large-scale tangles of vortex filaments that before final dissipation tend to decay to small-scale loops. A topological analysis of superfluid tangles shows that very complex knots and links are formed, and that upon mutual interaction and reconnection they gradually decompose to form small, unknotted, unlinked vortex rings [<a href='program#KKI16'>1</a>,<a href='program#CMBB19'>2</a>]. By using standard polynomials of knot theory derived from the fieldline helicity of vortex dynamics [<a href='program#RL23'>3</a>] we showed that our adapted polynomials can <i>quantify</i> the generic topological cascade observed in experiments [<a href='program#LRG24'>4</a>]. Here we present a topological approach to turbulence cascade based on the idea that the dynamical process could be viewed in terms of geodesic flows in an appropriate knot polynomial space (a discrete metric space), whose singletons represent knot types identified by their knot polynomial value [<a href='program#LRL20'>5</a>]. Optimal unlinking paths can thus be determined and put in relation with statistical measures of energy dissipation and information entropy. Work in this direction is in progress.<br/><br/>This is joint work with Xin Liu (Beijing University of Technology, P.R. China).<br/><br/><b>References</b><br/><br/><span id='KKI16'>[1] Kleckner, D., Kauffman, L.H.  &  Irvine, W.T.M. (2016) How superfluid vortex knots untie.</span> <i>Nature Physics</i> <b>12</b>, 650--655.<br/><span id='CMBB19'>[2] Cooper, R.G., Mesgarnezhad, M.,  Baggaley, A.W. & Barenghi, C.F. (2019)</span> Knot spectrum of turbulence. <i>Sci. Rep.</i> <b>9</b>, 10545.<br/><span id='RL23'>[3] Ricca, R.L. & Liu, X. (2023)</span> A new framework for the Jones polynomial of fluid knots. <i>J. Knot Theory & Its Ram.</i>, 2340024.<br/><span id='LRG24'>[4] Liu, X., Ricca, R.L. & Guan, H. (2024)</span> A topological approach to vortex knots and links. In <i>Knotted Fields</i> (ed. R.L. Ricca & X. Liu), pp. 1-36.  Lecture Notes in Mathematics <b>2344</b>, Springer-Nature, Switzerland.<br/><span id='LRL20'>[5] Liu, X., Ricca, R.L. & Li, X.-F. (2020)</span> Minimal unlinking pathways as geodesics in knot polynomial space. <i>Nature Comm. Physics</i> <b>3</b>, 136.",
            start: "2025-02-02T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Efstratia Kalfagianni",
            university: "",
            title: "Colored Jones polynomials and crossing numbers of satellite knots",
            description: "It has been long known that the quadratic term in the degree of the colored Jones polynomial of knot provides a lower bound of the crossing number the knot. I’ll discuss work, some joint with Christine Lee (2021) and some joint with Rob McConkey (2023), where we determine the class of knots for which this bound is sharp and  give applications to computing crossing numbers of satellite knots.",
            start: "2025-02-02T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "John Bryden",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-02T14:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 2
        {// plenary talk
          speaker: "Dror Bar-Natan",
          university: "University of Toronto",
          title: "The Strongest Genuinely Computable Knot Invariant Since 2024",
          description: "\"Genuinely computable\" means we have computed it for random knots with over 300 crossings. \"Strongest\" means it separates prime knots with up to 15 crossings better than the less-computable HOMFLY-PT and Khovanov homology taken together. And hey, it's also meaningful and fun. <br/><br/>Continues Rozansky, Garoufalidis, Kricker, and Ohtsuki, joint with Van der Veen.<br/><br/>More information: <a href='http://drorbn.net/ktc25'>http://drorbn.net/ktc25</a>",
          start: "2025-02-02T18:00:00Z",
          duration: 1.0,
        },
        [
          {
            speaker: "Boris Apanasov",
            university: "University of Oklahoma, Norman/OK, USA",
            title: "Nontrivial $2$-knots as everywhere wild quasisymmetric embeddings $S^2\\hookrightarrow S^4$ with ergodic dynamics of uniform hyperbolic lattices",
            description: "We discuss applications of our recently introduced conformal interbreeding (generalizing Gromov-Piatetskii hyperbolic interbreeding) to nontrivial $2$-knots in $4$-sphere and geometric analysis. Created $2$-knots in $S^4$ have ergodic dynamics of uniform hyperbolic lattices and are obtained by everywhere wild quasisymmetric embeddings $S^2\\hookrightarrow S^4$ equivariant with respect to the action of uniform hyperbolic lattices. This is connected to theory of conformal deformations of hyperbolic structures, their Teichmüller spaces (varieties of discrete reprs of hyperbolic lattices) and nontrivial homology $4$-cobordisms. For related material (negatively curved locally symmetric rank one spaces, their Teichmüller spaces, faithful (or not) discrete reprs of uniform hyperbolic lattices, hyperbolic 4-cobordisms and several their appls to algebra, geometry, topology and geometric analysis) we refer to our new book \"Dynamics of Discrete Group Action\" published last Summer by De Gruyter in the series Advances in Analysis and Geometry, <b>10</b>.",
            start: "2025-02-02T19:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Pedro M. G. Manchón",
            university: "",
            title: "A torsion pattern in Khovanov homology",
            description: "We will show specific sums of enhanced states that produce torsion of order two in the Khovanov homology. This is work related to the Shumakovitch conjecture which states that all links except the trivial knot, the Hopf link and their disjoint unions and connected sums have torsion.<br/><br/>Joint work with Raquel Díaz.",
            start: "2025-02-02T19:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Hugh Morton",
            university: "",
            title: "Framing and knot invariants",
            description: "Kauffman  focussed attention on the importance of treating framing separately when thinking of knot invariants. His construction of the bracket polynomial, and more strikingly of the Dubrovnik version of his 2-variable polynomial from the Brandt-Lickorish-Millett-Ho polynomial, made a key use of framing. At the same time he showed how framing works well with the Homfly polynomial, using a memorable set of skein relations.<br/><br/>Framing plays an essential role in constructing satellite knots and related invariants. It is also central in the behaviour of quantum group based invariants, and guides the best ways to compare diverse appearances of invariants.<br/><br/>I will recall Rudolph's early work relating Dubrovnik to the Homfly of a reverse parallel, pointing out the clean comparison when framing is kept in mind, and also the more general relation between coloured Dubrovnik and suitably coloured Homfly invariants.",
            start: "2025-02-02T19:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "José Carlos Gómez Larrañaga",
            university: "",
            title: "Tri-genus of $3$-manifolds, $2$-stratifolds and $3$-manifolds polynomials",
            description: "While studying the tri-genus of $3$-manifolds <a href=\"program#JoseCarlos_bib_1\">[1]</a> we found the first examples of $2$-stratifolds. In an informal way to say it, a $2$-stratifold is a finite $2$-dimensional simplicial complex that outside a link is a finite collection of surfaces. We present several results about $2$-stratifolds <a href=\"program#JoseCarlos_bib_2\">[2]</a>. We will mention two applications where $2$-stratifolds appear <a href=\"program#JoseCarlos_bib_3\">[3]</a>, <a href=\"program#JoseCarlos_bib_4\">[4]</a>. This part of the talk is joint work with F. González-Acuña and W. Heil.<br/><br/>Now, let $D = (S; A, B)$ be a $3$-manifold Heegaard Diagram (HD) of genus $n$. Let us call $G = A \\cup B$ the Heegaard graph of $D$ where $V = A \\cap B$ are the vertices of $G$ and $E = G - V$ are the edges of $G$. For any $D$ where $S - G$ is a finite collection of open disks, we can define a polynomial $p(D)$ of $D$ where $p$ is any graph polynomial of $G$ as those defined in <a href=\"program#JoseCarlos_bib_5\">[5]</a> (Tutte, Ribbon, …). We propose a way to use these graph polynomials to define $3$-manifolds polynomials. These polynomials can be calculated for Lens spaces. This second part of the talk is joint work J.A. Frías, F. Manjarrez and J. L. León.<br/><br/><b>References</b><br/><br/><span id=\"JoseCarlos_bib_1\">[1]</span> Heil, Wolfgang; Núñez, Víctor; Gómez-Larrañaga, J. C. Stiefel-Whitney surfaces and the tri- genus of non-orientable $3$-manifolds. Manuscripta Math. 100 (1999), no. 4, 405-422.<br/><span id=\"JoseCarlos_bib_2\">[2]</span> Gómez-Larrañaga, J.C., González-Acuña, F. & Heil, W. Stratworld. Bol. Soc. Mat. Mex. Accepted (2024).<br/><span id=\"JoseCarlos_bib_3\">[3]</span> Shawn Martin , Aidan Thompson, Evangelos A Coutsias, Jean-Paul Watson. Topology of cyclo-octane energy landscape. J Chem Phys 132(23):234115 (2010).<br/><span id=\"JoseCarlos_bib_4\">[4]</span> Ahtziri González-Lemus, Brayan Hernández-Calvillo, Karla P. Acosta Zamora, José Núñez González and Eduardo Ramos Mora. Topological data analysis of three dimensional orbits in a convective flow. Preprint (2024).<br/><span id=\"JoseCarlos_bib_5\">[5]</span> Joanna A. Ellis-Monaghan and Iain Moffatt. Graphs on Surfaces Dualities, Polynomials, and Knots. SpringerBriefs in Mathematics (2013).",
            start: "2025-02-02T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Raquel Díaz",
            university: "",
            title: "A torsion pattern in Khovanov homology, II",
            description: "We will show specific sums of enhanced states that produce torsion of order two in the Khovanov homology. This work is related to the Shumakovitch conjecture which states that all links except the trivial knot, the Hopf link and their disjoint unions and connected sums have torsion. Joint work with Pedro M.G. Manchón.",
            start: "2025-02-02T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Lowrance Adam",
            university: "",
            title: "Arc index and Turaev genus",
            description: "An arc presentation of a knot is an embedding of the knot in finitely many pages of an open-book decomposition such that the portion of the knot on each page is a single simple arc. The arc index of a knot is the minimum number of pages in any arc presentation of the knot. The Turaev surface of a knot diagram $D$ is constructed by first taking the cobordism between the all-A and all-B states of $D$ with saddle points corresponding to the crossings of $D$, and then capping off the boundary components of that cobordism with disks. The Turaev genus of a knot is the minimum genus of the Turaev surface for any diagram. In this talk, we discuss a relationship between the crossing number, arc index, and Turaev genus of a knot. This is joint work with Alvaro Del Valle Vilchez.",
            start: "2025-02-02T20:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 3
        {// plenary talk
          speaker: "Akio Kawauchi",
          university: "",
          title: "Ribbon Surface-Link Overview",
          description: "An overview of ribbon surface-links that have been studied by the speaker to date will be presented. Ribbon surface-links are identified with chord graphs, and are a relaxed version of virtual graphs including virtual knotoids with groups identified with the fundamental groups. If a stabilization of a surface-link is a ribbon surface-link, then any handle-irreducible summand of the stabilized surface-link is a ribbon surface-link which is determined uniquely from the surface-link up to equivalences and stabilizations. Many results are obtained by using this result together with several other results. A surface-link with free fundamental group is a stabilization of a ribbon sphere-link, and a trivial surface-link if the fundamental group is  meridian-based. A connected sum of surface-links is a ribbon surface-link if and only if both the connected summands are ribbon surface-links. A surface-link of trivial components is a ribbon surface-link if the components are sphere-components except for at most one component. It will be also explained how this argument is related to 4D and 3D Poincare conjectures, J. H. C. Whitehead aspherical conjecture, Kervaire conjecture on group weight and the slice-ribbon problem as time allows.",
          start: "2025-02-03T01:00:00Z",
          duration: 1.0,
        },
        [
          {
            speaker: "Kevin Walker",
            university: "",
            title: "Higher-dimensional Temperly-Lieb categories via partition relations",
            description: "I’ll define a family of pivotal $n$-categories $P(n,k, \\beta)$ whose morphisms are constructed out of codimension-$k$ submanifolds of balls.<br/<br/>$P_{2,1}$ reproduces Kauffman’s graphical version of the Temperly-Lieb tensor category. This talk will focus on $P_{3,1}$ (a $3$-category) and $P_{4,2}$ (a $4$-category). Each $P_{n,k}$ has an associated $(n+\\epsilon)$-dimensional TQFT. One can also take quotients by tensor ideals for a discrete set of parameter values $\\beta$ (analogous to setting a Jones-Wenzl idempotent to zero). Both $P_{3,1}$ and $P_{4,2}$ contain subcategories isomorphic to Deligne’s $Rep(S_t)$. They also contain many other $1$-parameter families of symmetric monoidal categories. It is an open question to what extent these symmetric monoidal categories are genuinely new.",
            start: "2025-02-03T02:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Mike Willis",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-03T02:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Eiji Ogasa",
            university: "",
            title: "Kauffman states and an extension of Khovanov-Lipshitz-Sarkar homotopy type",
            description: "It is an outstanding open question whether Jones polynomial (respectively, Khovanov homology, Khovanov-Lipshitz-Sarkar homotopy type) can be extended to all manifolds. They are originally defined in the case of the $3$-sphere.<br/><br/>Louis H. Kauffman, Igor Nikonov, and the speaker used  enhanced Kauffman states, and gave the first partial solution in the case of Khovanov-Lipshitz-Sarkar homotopy type. They defined it in the case of thickened surfaces.",
            start: "2025-02-03T02:00:00Z",
            duration: 1.0,
          }
        ],
        {// plenary talk
          speaker: "Edward Witten",
          university: "",
          title: "From the Jones Polynomial to Khovanov Homology Via Gauge Theory",
          description: "The original gauge theory description of the Jones polynomial involved a three-dimensional gauge theory based on a Chern-Simons action function. However, a \"dual\" four-dimensional gauge theory description gives a more direct interpretation of the coefficients of the Jones polynomial (viewed as a Laurent polynomial in a variable $q$) and provides a bridge to Khovanov homology.",
          start: "2025-02-03T03:00:00Z",
          duration: 1.0,
        },
      ]
    ],
    [// day 3
      [// part 1
        {// plenary talk
          speaker: "Vassily Manturov",
          university: "Moscow Institute of Physics and Technology",
          title: "The photography method: The state of the art and open problems.",
          description: "In 2023, the speaker formulated the photography method which allows one to solve various equations and construct invariants of various topological object. We start from some object (say, pentagon) and its state (say, triangulation) with some data (for example, edge lengths of  triangles) together with a transformation rule (say, a triangulation flip). After that, by using some geometrical consideration, one can \"automatically\" prove that such transformation lead to a solution of some equation (for example, the Ptolemy transormation givves a solution to the pentagon equation) which leads to invariants of various objects (for example, braids). After that, one can \"freely\" (without any calculations) get a formula coming from some geometrical data (say, lengths in the hyperbolic space). Having such a formula, one automatically gets its algebraic proof which allows one to pass from geometric objects (lengths, angles) to variables. This method is very vaste. In particular, Dijkgraaf-Witten invariants can be interpreted in terms of the photography method. We mention just some relations of further research: invariants of knots, braids, manifolds of arbitrary dimensions, solutions to the pentagon, Yang-Baxter and other equations, relations to cluster algebras, tropical geometry and other parts of mathematics.",
          start: "2025-02-03T12:00:00Z",
          duration: 1.0,
        },
        [// section 1
          {
            speaker: "Scott Baldridge",
            university: "",
            title: "A new way to prove the Four Color Theorem using gauge theory",
            description: "In this talk, I show how ideas coming out of gauge theory can be used to prove configurations in the list of \"633 unavoidable configurations\" are reducible. In particular, I show how to prove the smallest nontrivial example, the Birkhoff diamond (four adjacent pentagons), is reducible using our filtered $3$- and $4$-color homology. In this context reducible means that the Birkhoff diamond cannot show up as a \"tangle\" in a minimal counterexample to the four color theorem. This is a new proof of a 111-year-old result that is a direct consequence of a special $(2+1)$-dimensional topological quantum field theory. If time, I will indicate how the ideas used in the proof might be used to reduce the four color theorem to a human computable calculation.<br/><br/>This is joint work with Ben McCarty.",
            start: "2025-02-03T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "María Teresa Lozano",
            university: "",
            title: "On integral groups and 3-dimensional orbifolds",
            description: "In this talk I will remind the concept of integral group for a group of matrices in a number field $K$. This is a necessary condition to be an arithmetic group. Some examples of 3-dimensional orbifolds with knots or links as singular set whose fundamental group is an integral group will be presented. I will also state some open questions.<br/><br/>Partially based on: M.T. Lozano, J.M.Montesinos-Amilibia: “Integral geometric orbifolds”.  J. Knot Theory Ramifications 30 (2021), no. 12, Paper No. 2141010.",
            start: "2025-02-03T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Dušan D. Repovš",
            university: "Faculty of Mathematics and Physics, University of Ljubljana, Jadranska 19, Ljubljana, Slovenia",
            title: "Applications of Kauffman’s polynomial: Nonstandard embeddings of the Cantor set into $\\mathbb{R}^{3}$",
            description: "In the last 20 years there has been a revival of interest in constructions of wild Cantor sets in $\\mathbb{R}^{3}$ which were first discovered a century ago. These new wild examples have some additional properties, for example Lipschitz homogeneity in $\\mathbb{R}^{3},$ rigidity in $\\mathbb{R}^{3},$ simple connectivity of the complement in $\\mathbb{R}^{3},$ etc. We shall consider such a construction where the Kauffmann bracket polynomial is used to establish its properties. We shall also state some open problems and conjectures.",
            start: "2025-02-03T13:00:00Z",
            duration: 1.0,
          }
        ],
        [// section 2
          {
            speaker: "Maria Rita Casali",
            university: "",
            title: "Kirby diagrams, trisections and gems of $PL$ $4$-manifolds",
            description: "The talk reviews the main achievements regarding the interactions between gem theory (which makes use of edge-colored graphs to represent $PL$-manifolds of arbitrary dimension) and both the classical representation of $PL$ $4$-manifolds via Kirby diagrams and the more recent one via trisections.<br/><br/> In particular, algorithmic procedures are presented to pass from one representation to the other, allowing to yield estimations of the involved invariants, as well as to produce examples of triangulations of exotic $4$-manifolds. <br/><br/>Joint work with Paola Cristofori.",
            start: "2025-02-03T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Ljubica Velimirovic",
            university: "",
            title: "Shape and energies of geometric objects",
            description: "To study energies and shape of geometrical objects, namely of surfaces, curves and knots, we use curvature and  curvature based functionals, Willmore energy, total curvature, total torsion, total normalcy and Möbius energy. We investigate infinitesimal bending using Differntial geometry.<br/><br/>The talk is based on the book with the same title prepared by professor Kauffman, L. Velimirovic, M. Najdanovic and S. Rancic, and the papers based on reasrch of the same authors. ",
            start: "2025-02-03T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Bartosz Gren",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-03T14:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 2
        {// plenary talk
          speaker: "Sofia Lambropoulou",
          university: "",
          title: "Celebrating Lou Kauffman: Working with Lou",
          description: "",
          start: "2025-02-03T17:00:00Z",
          duration: 1.0,
          type: 'birthday'
        },
        {// plenary talk
          speaker: "Louis Kauffman",
          university: "",
          title: "Multiple Virtual Knot Theory",
          description: "This talk will discuss a version of virtual knot theory in which there can be any number of distinct types of virtual crossings, each type can detour over any other type and over the classical crossings. The original motivation for this construction was a two virtual construction of the speaker that generalizes the Penrose coloring evaluation of planar trivalent graphs to arbitrary trivalent graphs. The talk will begin with these motivations, dwell on colorings and how they are related to knot and link diagrams. Then the talk will discuss generalized bracket polyomials, arrow polynomials, generalized quandles and other invariants for multiple virtuals.",
          start: "2025-02-03T18:00:00Z",
          duration: 1.0,
        },
        [
          {
            speaker: "Paolo Bellingeri",
            university: "University of Caen Normandy, France",
            title: "Congruence subgroups of braid groups and crystallographic quotients",
            description: "This talk delves into the relationship between two families of groups, respectively subgroups and quotients of classical braid groups: congruence subgroups of braid groups and crystallographic braid groups, respectively introduced Arnol'd and Tits. We recall and introduce some elements belonging to congruence braid groups and we establish some (iso)-morphisms between crystallographic braid groups and corresponding quotients of congruence braid groups. Finally, we study the lower central series of congruence braid groups related to the braid group B3, showing in particular that corresponding quotients are all almost crystallographic.<br/><br/>Joint work with C. Damiani, O. Ocampo, and C. Stylianakis.",
            start: "2025-02-03T19:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Joan Porti Pique",
            university: "",
            title: "Schemes of characters",
            description: "The variety of $\\mathrm{SL}_2(\\mathbb C)$  is naturally an affine scheme, namely a subset of $\\mathbb C^n$ defined by a polynomial ideal that may be non radical. In particular points may have multiplicity. In this talk I shall show how those multiple points appear naturally in geometric structures on  branched coverings of knots and links.  I also shall discuss the \"scheme version\" of a theorem of Fico and Montesinos on how to compute the variety of characters.",
            start: "2025-02-03T19:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "De Witt Sumners",
            university: "",
            title: "Helicity of Seifert Framed Defects",
            description: "The topology and helicity of anti-parallel defect reconnection will be discussed. Line defects are one-dimensional phase singularities (forming oriented knots and links) that arise in a variety of physical systems (fluid dynamics, magnetic fields, excitable media). In these systems, isophase surfaces (Seifert surfaces) have the phase defects as boundary, and these Seifert surfaces define a framing of the normal bundle of each link component. We define the individual helicity for each component of a link singularity, and prove that each individual helicity is zero if and only if there exists a Seifert framing for the link. We extend these results to multi-armed defects. We prove that under anti-parallel reconnection of framed defect strands that both twist and writhe helicity are conserved.<br/><br/><b>References<br/><br/></b>C. E. Laing, Renzo L. Ricca, D.W. Sumners, Conservation of writhe helicity under anti-parallel reconnection, <i>Nature Scientific Reports</i> 5 : 9224 DOI: 10.1038/srep09224 (2015).<br/>D.W. Sumners, I. Cruz-White, R. Ricca, Zero Helicity of Seifert Framed Defects, <i>J. Phys A, Math. Theor.</i> <b>54</b> (2021) 295203",
            start: "2025-02-03T19:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "Michel Boileau",
            university: "",
            title: "$\\pi$-orbifold group and symmetric union",
            description: "The symmetric union is a construction introduced by Kinoshita and Terasaka in 1957 and generalized by Lamm in 2000. This construction is a wide generalization of the connected sum of a knot with its mirror image which produces ribbon knots. It is still an open question whether every ribbon knot admits a symmetric union presentation. The $\\pi$-orbifold group of a knot $K$ in $S^3$ is the quotient of the knot group by the subgroup normally generated by the square of a meridian. In this talk we will use the $\\pi$-orbifold group to discuss this question and the relationship between the knot type of a symmetric union and of its partial knot.<br/><br/>This is a work in progress with Teruaki Kitano  and Yuta Nozaki.",
            start: "2025-02-03T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Masahico Saito",
            university: "University of South Florida",
            title: "Heaps, Yang-Baxter Hochshild Cohomology and Surface Ribbons in $3$-space",
            description: "Surface ribbons are compact orientable surfaces with boundary embedded in 3-space, that are represented by diagrams of thin ribbons in the plane. They can be also represented by graph diagrams by taking the spine of ribbons. Their moves for isotopy are known in terms of graph moves. A group heap is a group with the ternary self-distributive operation defined by $(x,y,z) \\mapsto xy^{-1}z$. We show that the fundamental heap is defined for surface ribbons by group presentations from their graph diagrams. Further, the Hopf algebra version of heaps are used to construct braided Frobenius algebras, that are associative algebras with the Yang-Baxter operators (YBO), such that multiplications and YBO satisfy compatibility conditions that correspond to graph moves. For such algebras with YBO, Yang-Baxter Hochschild cohomology is defined from deformations, unifying the two theories. The talk will provide an overview of joint work with Emanuele Zappala  on these algebraic structures related to surface ribbons.",
            start: "2025-02-03T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Paweł Traczyk",
            university: "University of Warsaw, Warsaw, Poland, <a href='mailto:traczyk@mimuw.edu.pl'>traczyk@mimuw.edu.pl</a>",
            title: "Burau braid representation for $n = 4$. A problem in linear algebra?",
            description: "We consider the problem of faithfulness of the famous Burau braid representation $\\rho$ for $n = 4.$<br/>It is known to be equivalent to the problem of whether certain two matrices $\\alpha$ and $\\beta$ (given below) generate a free group of rank two. $$ \\alpha = \\left[ \\begin{array}{ccc}0 & 0 & -t^{-1} \\\\ 0 & -t & -t^{-1} + t\\\\  -1 & 0 & -t^{-1} + 1 \\end{array}\\right]  \\beta =\\left[ \\begin{array}{ccc}-t & t & 0 \\\\ 0 & 1 & 0 \\\\ 0 & t^{-1} & -t^{-1} \\end{array}\\right]$$It turns out that this can be reduced to the following seemingly simpler problem:<br/>Let us consider the following six matrices:$$\\rho(\\sigma_3\\sigma_2\\sigma_1) = ~~~\\left[\\begin{array}{rrrr} -t & t & 0\\\\ -t & 0 & t\\\\ -t & 0 & 0 \\end{array}\\right] = S,(and S^2,S^3)~~~and~~~\\rho(\\sigma_1\\sigma_2\\sigma_3) = \\left[\\begin{array}{rrlr} 0 & 0 & -t^3\\\\ 1 & 0 & -t^2\\\\ 0 & 1 & -t \\end{array} \\right] = B(and B^2, B^3).$$ The problem of faithfulness of the Burau representation is equivalent to the question wheather or not it is possible to obtain (for some positive integer $k$) the diagonal matrix $$\\left[\\begin{array}{ccc} t^{4k} &      0 & 0\\\\ 0      & t^{4k} & 0\\\\ 0      &      0 & t^{4k} \\\\ \\end{array} \\right]$$ as an alternating product of the above mentioned six matrices. Alternating means that $S,S^2,S^3$ and $B,B^2,B^3$ appear in an alternating manner.<br/><br/>In the talk we will discuss some experimental data and consider somr typical and some exceptional examples. It is actually true that the only chance is to have $4k$ in the matrix above equal to the sum of exponents of $B,B^2,B^3,S,S^2,S^3.$ We conjecture that in fact the considered product will always contain, in one of the entries, a term $t^m, m < 4k.$",
            start: "2025-02-03T20:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 3
        {// plenary talk
          speaker: "Ciprian Manolescu",
          university: "",
          title: "Generalizations of Rasmussen's invariant",
          description: "Over the last 20 years, the Rasmussen invariant of knots in $S^3$ has had a number of interesting applications to questions about surfaces in $B^4$. In this talk I will survey some recent extensions of the invariant to knots in other three-manifolds: in connected sums of $S^1 \\times S^2$ (joint work with Marengon, Sarkar, and Willis), in $RP^3$ (joint work with Willis, and also separate work of Chen), and in a general setting (work by Morrison, Walker and Wedrich; and independently by Ren-Willis). I will describe how these invariants give bounds on the genus of smooth surfaces in $4$-manifolds, and can even detect exotic $4$-manifolds with boundary.",
          start: "2025-02-04T01:00:00Z",
          duration: 1.0,
        },
        [
          {
            speaker: "Robert Owczarek",
            university: "University of New Mexico",
            title: "Cartan philosophy on geometry, and TQFTs defined for theories of Sławianowski and Kijowski type",
            description: "We confront the philosophy of Cartan on different geometries used in \"physics\" (mostly general relativity) with the philosophy of Topological Quantum Field Theories used to construct topological invariants of manifolds and structures within them (e.g., knots and links in $3D$ manifolds). We show that applying Cartan philosophy to manifolds of general dimension, gives for Topological Quantum Field Theories of the \"non-metric\" type (so, of the type including Chern-Simons theories in $3D$) basically just two possibilities, which we call theories of Sławianowski type, and Kijowski type, named after their creators (more exactly, it will be slight variation from their original theories, but obviously equivalent). We will construct the proper Lagrangian of the theories, and, in the spirit of Chern-Simons theories, we will write down \"topological invariants\" as appropriate path integrals. We will shortly discuss the difficulty of further analysis of so obtained invariants.",
            start: "2025-02-04T02:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Scott Carter",
            university: "",
            title: "Folding Branched Covers of the $3$-sphere into $4$ and $5$-space",
            description: "Let $M$ denote a cyclic or dihedral branched cover of the $3$-sphere that is branched over a knot or link. In the dihedral case, there is an embedding  of $M$ into $S^3\\times [0,n+1]\\times [-1,1]$ such that the projection onto $S^3$ induces the covering. Here $n$ is the degree of the covering. In the dihedral case, say $D_n$ is the dihedral group that has $2n$ elements. Then there is a map from $M$ into $S^3\\times [0,n+1]$ that is a general position immersion away from the branch set, and such that the projection onto $S^3$ induces the covering. The images of the branched covers are what we call foldings.<br/><br/>This is joint work with Byeorhi Kim and Seonmi Choi.",
            start: "2025-02-04T02:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Liu peng yu,",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-04T02:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "Hanna Makaruk",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-04T03:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Sergei Melikhov",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-04T03:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Jonathan Schneider",
            university: "",
            title: "Roto-Welded Knot Theory (revisited)",
            description: "Roto-Welded Knot Theory is a diagrammatic theory similar to Virtual Knot Theory, except that one of Virtual's forbidden $III$-moves is now permitted, and one of Virtual's permitted I-moves is now forbidden. Roto-Welded knot types are in bijective correspondence with certain classes of toral surfaces in $4$-space, called fiberwise-embedded surfaces. This talk revisits some of the results from a 2018 study by Kauffman, Ogasa, and myself, based on an idea of Satoh and Rourke.",
            start: "2025-02-04T03:00:00Z",
            duration: 1.0,
          }
        ]
      ]
    ],
    [// day 4
      [// part 1
        {// plenary talk
          speaker: "Vladimir Turaev",
          university: "",
          title: "Knots and links in 2-complexes",
          description: "We introduce and study knots and links in $2$-dimensional complexes. In particular, we define linking numbers for oriented two-component links in $2$-complexes and a Kauffman-type bracket polynomial for links in $2$-complexes. We also discuss relationships with knots and links in $3$-manifolds.",
          start: "2025-02-04T12:00:00Z",
          duration: 1.0,
        },
        [// section 1
          {
            speaker: "Nikolai Abrosimov",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-04T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Ruth Lawrence",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-04T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Dorothy Buck",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-04T13:00:00Z",
            duration: 1.0,
          }
        ],
        [// section 2
          {
            speaker: "John Guaschi",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-04T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Rubén Vigara",
            university: "",
            title: "Filling Dehn surfaces in $3$-manifolds",
            description: "Dehn surfaces are immersed surfaces in $3$-manifolds with only double curve and triple point singularities. A Dehn surface <i>fills</i> the $3$-manifold $M$ where it lies if it defines a cell decomposition of $M$ in a natural way. Filling Dehn <i>spheres</i>, and their Johansson diagrams, where proposed by Montesinos in 2000 as a suitable way  for representing all closed, orientable, $3$-manifolds. Since then, some advances have been made in the subject, relating filling Dehn spheres (and surfaces) with areas as  $3$-manifold complexity or $2-$ and $1-$knots, for example. We'll present the subject and these advances, together with future research lines and some open questions. This is a joint work with Álvaro Lozano.",
            start: "2025-02-04T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Anastasiia Tsvietkova",
            university: "",
            title: "On embedded essential surfaces in alternating links, other links, and other $3$-manifolds",
            description: "For a low-dimensional manifold, one often tries to understand its intrinsic topology through its submanifolds, in particular of codimension 1. For a $3$-manifold, embedded essential surfaces give information about that manifold. However to construct, classify or count such surfaces is a non-trivial task. Since the 1980s, it has been known that essential surfaces in alternating link complements in $3$-sphere can be isotoped to be \"almost\" transverse to the link diagram, and described combinatorially as a result. This was called standard position for surfaces, due to Menasco and Menasco-Thistlethwaite for various types of surfaces, and has had numerous applications. With Jessica Purcell, we extended standard position for surfaces to a broad class of cusped $3$-manifolds. The manifolds include links that are alternating on higher genus surfaces, and lie in manifolds besides the $3$-sphere, e.g. many virtual links and toroidally alternating links. Applications of these techniques include polynomial upper bound on the number of surfaces embedded in such $3$-manifolds and their Dehn fillings. The bound is universal: there is explicit formula that depends on three known parameters, which describe topology of the surface and $3$-manifold. Another related new result goes beyond links: a universal upper bound for the number of surfaces embedded in any hyperbolic $3$-manifold, closed or cusped, polynomial in hyperbolic volume. For this, different techniques had to be developed, blending minimal and normal surface theory.<br/><br/>The latter is joint work with Marc Lackenby.",
            start: "2025-02-04T14:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 2
        {// plenary talk
          speaker: "Lisa Piccirillo",
          university: "",
          title: "New constructions and invariants of closed smooth $4$-manifolds",
          description: "Dimension four is the lowest dimension where smooth and topological manifolds can differ; any difference between these categories is known as exotica. In particular, a smooth $4$-manifold is <i>exotic</i> if there is another smooth $4$-manifold which is homeomorphic but not diffeomorphic to it. There is a wealth of literature, mostly written between 1983 and 2008, on producing exotic manifolds, but the techniques pioneered in this era can be hard to use in practice. I will discuss joint work with Adam Levine and Tye Lidman in which we give some new techniques for producing exotic $4$-manifolds.",
          start: "2025-02-04T18:00:00Z",
          duration: 1.0,
        },
        [
          {
            speaker: "Xian'an Jin",
            university: "School of Mathematical Sciences, Xiamen University, Xiamen, P. R. China, <a href=mailto:xajin@xmu.edu.cn>xajin@xmu.edu.cn</a>",
            title: "Twist polynomial as a weight system",
            description: "This talk contains five parts. First we give a brief introduction to the knot theoretic background. In the second part, we give the definitions of ribbon graphs and their partial-dual (genus) polynomials, and some progress in this topic. Then based on Chmutov's work we prove the partial dual polynomial as a function of framed chord diagrams satisfies three four-term relations, thus can be viewed as a weight system. In the fourth part, we extend the above results to set systems and their twist (width) polynomials, i.e. introduce the $4$-term relation of set systems and prove the twist polynomial satisfies it. In the last part, several remarks are given.",
            start: "2025-02-04T19:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "William W. Menasco",
            university: "",
            title: "A Seifert algorithm for integral homology spheres",
            description: "This talk is based on recent joint work Linda V. Alegria.<br/><br/>From classical knot theory we know that every knot in $S^3$ is the boundary of an oriented, embedded surface.  A standard demonstration of this fact achieved by elementary technique comes from taking a regular projection of any knot and employing Seifert's constructive algorithm.  In this note we give a natural generalization of Seifert's algorithm to any closed integral homology $3$-sphere.  The starting point of our algorithm is presenting the handle structure of a Heegaard splitting of a given integral homology sphere as a planar diagram on the boundary of a $3$-ball. (For a well known example of such a planar presentation, see the Poincaré homology sphere planar presentation in <i>Knots and Links</i> by Dale Rolfsen).  An oriented link can then be represented by the regular projection of an oriented $k$-strand tangle.  From there we give a natural way to find a \"Seifert circle\" and associated half-twisted bands.",
            start: "2025-02-04T19:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Igor Nikonov",
            university: "",
            title: "The crossing and the arc from the topological viewpoint",
            description: "Combinatorial approach to knot theory treats knots as diagrams modulo Reidemeister moves. Many constructions of knot invariants (e.g., index polynomials, quandle colorings etc.) use elements of diagrams such as arcs and crossings by assigning invariant labels to them. The universal invariant labels, which carry the most information, can be thought of as equivalence classes of arcs and crossings modulo the relation, which identifies corresponding elements of diagrams connected by a Reidemeister move. One can call these equivalence classes the arcs and crossings of the knot. In the talk we give a topological description of sets of these classes.",
            start: "2025-02-04T19:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "Thomas Fiedler",
            university: "",
            title: "Distinguishing knots without invariants",
            description: "Let $(D,p)$ and $(D',p')$ be two diagrams of long framed knots with a chosen crossing $p$ respectively $p'$ in them. First we construct a series of combinatorial 1-cocycles in the moduli space of 2-cables of long framed knots. Then we apply them to canonical arcs in this moduli space in order to define integer invariants of the couple of crossings $(p,p')$. If these invariants do not satisfy a certain system of equations then the diagrams $D$ and $D'$ represent different knots.",
            start: "2025-02-04T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Pedro Lopes",
            university: "",
            title: "A combinatorial view on quandles",
            description: "Quandles are the algebraic distillations of the Reidemeister moves on diagrams. This renders them useful in the telling apart of knots.<br/><br/>We are thus lead to study their structure. Right-invertibility (quandles' 2nd axiom) allows us to regard them as sequences of permutations, the right translations.<br/><br/>It has been interesting to look into finite quandles by way of the cycle decomposition these right translations may have. Hayashi's conjecture states that, for connected quandles, the length of any of the disjoint cycles divides the length of the longest one. In this talk we report on work done on this topic with Lages, Vojtěchovský and Singh.",
            start: "2025-02-04T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Christian Blanchet",
            university: "Université Paris Cité and Sorbonne Université, CNRS, IMJ-PRG, F-75006 Paris, France",
            title: "Homology of configurations in ribbon graphs",
            description: "We review Heisenberg homology of configurations in once bounded surfaces and extend the construction to the regular thickening of a finite graph with ribbon structure.",
            start: "2025-02-04T20:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 3
        {// plenary talk
          speaker: "Cameron Gordon",
          university: "",
          title: "The Unknotting Problem for Surfaces in the $4$-sphere",
          description: "We determine explicit integers $g_1$ and $g_2$ such that if $g$ is at least $g_1$ (resp. $g_2$) then there is no algorithm to decide whether or not a closed, orientable, PL locally flat surface in $S^4$ of genus $g$ is PL (resp. TOP) unknotted. We also give analogous results for non-orientable surfaces.",
          start: "2025-02-05T01:00:00Z",
          duration: 1.0,
        },
        {// plenary talk
          speaker: "Peter Ozsvath",
          university: "",
          title: "Bordered Floer homology",
          description: "Heegaard Floer homology is an invariant for closed three-manifolds, introduced in collaboration with Zoltan Szabo. Formally, it is a module over the polynomial algebra in a formal variable $U$.  Bordered Floer homology is an invariant for low-dimensional manifolds, introduced in collaboration with Robert Lipshitz and Dylan Thurston. The bordered theory associates an algebra to a parameterized surface. To a three-manifold with boundary, it associates a module over the algebra of its boundary. To a closed three-manifold equipped with a separating surface, it expresses the Heegaard Floer homology as a tensor product of the modules associated to the two pieces. In fact, the original version of bordered Floer homology expresses the $U=0$ specialization of Heegaard Floer homology. I will outline work in progress with Robert Lipshitz and Dylan Thurston, addressing the algebraic and analytic challenges for generalizing the construction to the unspecialized setting.",
          start: "2025-02-05T02:00:00Z",
          duration: 1.0,
        },
        [
          {
            speaker: "Rama Mishra",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-05T03:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Makoto Sakuma",
            university: "OCAMI, Osaka Metropolitan University; Hiroshima University",
            title: "Invariant Seifert surfaces for strongly invertible knots",
            description: "By a <i>strongly invertible knot</i>, we mean a pair $(K,h)$ consisting of a knot $K \\subset S^3$ and an involution $h$ on $(S^3,K)$ such that $\\operatorname{Fix}(h)\\cong (S^1, S^0)$. In this talk, we first observe that the classical result of Edmonds, concerning the existence of an invariant <i>minimal genus</i> Seifert surface for <i>periodic knots</i>, does not hold for strongly invertible knots. However, as independently observed by Hiura and Boyle-Issa, every strongly invertible knot admits an invariant Seifert surface.<br/><br/>Note that if $S$ is an invariant Seifert surface for $(K,h)$, then $\\delta:=S\\cap \\operatorname{Fix}(h)$ is one of the two subarcs of $\\operatorname{Fix}(h)\\cong S^1$ bounded by $K\\cap \\operatorname{Fix}(h)\\cong S^0$. We call the triple $(K,h,\\delta)$  a <i>labeled strongly invertible knot</i> and define its {\\it equivariant genus} $g(K,h,\\delta)$ as the minimal genus of invariant Seifert surfaces for $(K,h,\\delta)$.<br/><br/>Our main result is the determination of the equivariant genera of all labeled strongly invertible knots whose underlying knots are $2$-bridge knots. This result, in particular, implies that for any pair of positive integers $(g,\\hat g)$ with $g\\le \\hat g$, there is a marked strongly invertible knot $(K,h,\\delta)$ such that $(g(K), g(K,h,\\delta))=(g,\\hat g)$.  This is joint work with Mikami Hirasawa and Ryota Hiura, as presented in the papers arXiv:2206.02097 [math.GT] and arXiv:2312.06156 [math.GT].",
            start: "2025-02-05T03:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Eleni Panagiotou",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-05T03:00:00Z",
            duration: 1.0,
          }
        ]
      ]
    ],
    [// day 5
      [// part 1
        [
          {
            speaker: "Neslihan Gügümcü",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-05T12:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Joanna Sułkowska",
            university: "",
            title: "Non-trivial topology in biology based on AI application",
            description: "",
            start: "2025-02-05T12:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Ioannis Diamantis",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-05T12:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "Gyo Taek Jin",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-05T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Kanako Oshiro",
            university: "",
            title: "Minimum numbers of Dehn colors of knots and symmetric local biquandle cocycle invariants",
            description: "In this talk, we give a method to evaluate minimum numbers of Dehn colors for knots by using symmetric local biquandle cocycle invariants. In particular, we show that there exist knots which are distinguished by minimum numbers of Dehn colors.<br/><br/>This is a joint work with Eri Matsudo and Gaishi Yamagishi.",
            start: "2025-02-05T13:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Paolo Cavicchiolli",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-05T13:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "Kenneth Millett",
            university: "",
            title: "The HOMFLY-PT polynomials and the Conway and Kinoshita-Terasaka Knots",
            description: "Following a brief review of what on knows about these knots, a description of Some ideas about how one might employ knot polynomials to extract finer aspects of the conformations.",
            start: "2025-02-05T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Stefan Klaus",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-05T14:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Valeriy Bardakov",
            university: "",
            title: "TBA",
            description: "",
            start: "2025-02-05T14:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 2
        {// plenary talk
          speaker: "Zoltan Szabo",
          university: "",
          title: "Knot Floer homology and Kauffman states",
          description: "The goal of this lecture is to explain the relationship between constructions in knot Floer homology, and the Kauffman states for the Alexander polynomial. The lecture will also include some advances on computations for knot Floer homology. It is a joint work with Peter Ozsvath.",
          start: "2025-02-05T18:00:00Z",
          duration: 1.0,
        },
        [
          {
            speaker: "Allison Henrich",
            university: "",
            title: "One Dimensional Families of Riemann Surfaces with Automorphisms",
            description: "The moduli space $\\mathcal{M}_{g}$ of surfaces of genus $g\\geq 2$ is the space of conformal equivalence classes of closed Riemann surfaces of genus $g$. This space is a complex, quasi-projective variety of dimension $3g-3$, and geometrically an orbifold under the action of the modular group. The set of singular points, the <i>branch locus</i>, may be stratified into a finite, disjoint union of smooth, irreducible, quasi-projective subvarieties called <i>equisymmetric strata</i>. Each stratum corresponds to a collection of surfaces of the same <i>symmetry type</i>, i.e. the conjugacy class of a finite group in the modular group.<br/><br/>The (complex) 1D strata are Riemann surfaces with punctures. We study these strata as punctured Riemann surfaces, in terms of the action of the automorphism group of the surfaces in the stratum. In this way the strata can be constructed, a la Hurwitz, as (branched) coverings of the Riemann sphere with four punctures or a torus with one puncture. We see that such strata are in fact Belyi curves. It will be interesting to see which ones are given by regular dessins d'enfants.",
            start: "2025-02-05T19:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Jozef H. Przytycki",
            university: "",
            title: "Homology of Yang-Baxter operators: from Lou Kauffman \"Braids\" paper to  HOMFLYPT Yang-Baxter homology.",
            description: "In the Spring of 1984 I traveled to Zaragoza to visit Josè Montesinos. I was, then, working  on incompressible surfaces (with Maite Lozano) and I just discovered  the (conjectural) smallest volume hyperbolic 3-manifold. I talked about these topics in Zaragoza. However,  Josè also showed me notes by Lou Kauffman, who visited Zaragoza before me. The notes were the base of the future book \"On Knots\".<br/><br/>What caught my attention was reference to the work by physicists Ball and Metha on an inductive proof of the existence of the Alexander polynomial. Lou incorporated in the notes an outline of the proof. Few months later we were able to prove (with Paweł Traczyk in November-December 1984) the existence of the generalized Jones (HOMFLYPT) link polynomial invariant. Almost 30 years later (in 2012) I was able to define/construct the homology of a general Yang-Baxter operator (in friendly competition with Victoria Lebed). I am now computing with my students and grand-students homology of the HOMFLYPT Yang-Baxter operator. In my talk I describe my winding path from 1984 till 2025, from Lou Kauffman hint to Yang-Baxter homology.",
            start: "2025-02-05T17:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Elisabetta Matsumoto",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-05T19:00:00Z",
            duration: 1.0,
          }
        ],
        [
          {
            speaker: "Francis Bonahon",
            university: "University of Southern California and Michigan State University",
            title: "Invisible $\\mathrm{SL}_n$-skeins",
            description: "For a Lie group $G$, the $G$-skein module of a $3$-dimensional manifold $M$ is a fundamental object in Witten’s interpretation of quantum knot invariants in the framework of a topological quantum field theory. When $G=\\mathrm{SL}_2$, the $\\mathrm{SL}_2$-module is better known as the Kauffman bracket skein module, and is closely related to the Jones polynomial. When the quantum parameter $q$ is a root of unity, the $\\mathrm{SL}_n$-skein module contains elements with a surprising “invisibility” property, in the sense that they can be traversed by any other skein without changing the resulting total skein. I will give a brief description of these invisible elements, based on the classical theory of symmetric polynomials in $n$ variables.",
            start: "2025-02-06T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Thomas Kindred",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-06T20:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Ivan Dynnikov",
            university: "",
            title: "Rectangular diagrams of links, surfaces, and foliations",
            description: "The formalism of rectangular diagrams provides a convenient framework for representing links and surfaces in the three-sphere in a consistent manner. They appear to have a strong connection with contact topology, as well as nice combinatorial properties, which make them useful for solving algorithmic and classification problems of knot theory. In particular, they allow to construct a particularly simple algorithm for recognizing the unknot and to solve the problem of algorithmic classification of Legendrian and transverse links. One can also use rectangular diagrams to obtain explicit presentations of finite depth taut foliations in link complements.",
            start: "2025-02-06T20:00:00Z",
            duration: 1.0,
          }
        ]
      ],
      [ // part 3
        {// plenary talk
          speaker: "Nicolai Reshetikhin",
          university: "",
          title: "Invariants of tangles with a flat connection in the complement",
          description: "The construction of these invariants based on properties of quantum groups at roots of unity was proposed in joint work with R. Kashaev. It is related to homotopy quantum field theory by V. Turaev. In this talk, I will recall the construction of these invariants, will  make a summary of a recent joint work with C. McPhail-Snyder and will explain why Poisson structures on the center of quantum groups at a root of unity that appear in this construction are natural from the geometry of flat connections in the complement to a tangle.",
          start: "2025-02-06T01:00:00Z",
          duration: 1.0,
        },
        [// section 1
          {
            speaker: "Colin Adams",
            university: "",
            title: "Hyperbolicity and Volumes of Charm Bracelets",
            description: "We consider a specific subset of staked links called charm bracelets and discuss a variety of results about when they are hyperbolic and what we can say about their volumes.",
            start: "2025-02-06T02:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Carmen Caprau",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-06T02:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Speaker Name",
            university: "",
            title: "Free time slot",
            description: "Free time slot",
            start: "2025-02-06T02:00:00Z",
            duration: 1.0,
          }
        ],
        [// section 2
          {
            speaker: "Alexander Mednykh",
            university: "",
            title: "TBA",
            description: "TBA",
            start: "2025-02-06T03:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Speaker Name",
            university: "",
            title: "Free time slot",
            description: "Free time slot",
            start: "2025-02-06T03:00:00Z",
            duration: 1.0,
          },
          {
            speaker: "Speaker Name",
            university: "",
            title: "Free time slot",
            description: "Free time slot",
            start: "2025-02-06T03:00:00Z",
            duration: 1.0,
          }
        ]
      ]
    ]
  ]
};
